/**
 * Style-property tables used by {@link DiagramExportService} to shrink SVG
 * exports. `html-to-image` inlines each element's *entire* computed style (~490
 * CSS declarations), which dominates the file size, so the exported markup is
 * pruned against these tables. Kept separate from the service to keep it readable.
 */

/**
 * The only properties kept on each element when pruning an exported SVG. For a
 * static image we only need what affects how it looks; dropping a property just
 * means it renders at its default in the standalone file, so the list errs on
 * the side of inclusion. Chrome's computed `cssText` emits some values as
 * shorthands (`grid`, `flex-flow`, `border`, `padding`, …), so both shorthand
 * and longhand forms are listed.
 */
export const KEEP_STYLE_PROPS = new Set<string>([
  // Text (mostly inherited)
  'color',
  'font',
  'font-family',
  'font-size',
  'font-weight',
  'font-style',
  'font-variant',
  'font-stretch',
  'font-feature-settings',
  'font-kerning',
  'line-height',
  'letter-spacing',
  'word-spacing',
  'text-align',
  'text-align-last',
  'text-transform',
  'text-decoration',
  'text-decoration-line',
  'text-decoration-style',
  'text-decoration-color',
  'text-decoration-thickness',
  'text-underline-offset',
  'text-indent',
  'text-overflow',
  'text-shadow',
  'white-space',
  'white-space-collapse',
  'word-break',
  'overflow-wrap',
  'word-wrap',
  'hyphens',
  'direction',
  'unicode-bidi',
  'writing-mode',
  'vertical-align',
  'tab-size',
  'line-clamp',
  '-webkit-text-fill-color',
  '-webkit-text-stroke',
  '-webkit-text-stroke-width',
  '-webkit-text-stroke-color',
  '-webkit-font-smoothing',
  '-webkit-line-clamp',
  '-webkit-box-orient',
  // Background
  'background',
  'background-color',
  'background-image',
  'background-position',
  'background-position-x',
  'background-position-y',
  'background-size',
  'background-repeat',
  'background-origin',
  'background-clip',
  'background-attachment',
  'background-blend-mode',
  '-webkit-background-clip',
  // Border (Chrome's computed cssText emits shorthands, so keep both forms)
  'border',
  'border-width',
  'border-style',
  'border-color',
  'border-radius',
  'border-top',
  'border-right',
  'border-bottom',
  'border-left',
  'border-top-width',
  'border-right-width',
  'border-bottom-width',
  'border-left-width',
  'border-top-style',
  'border-right-style',
  'border-bottom-style',
  'border-left-style',
  'border-top-color',
  'border-right-color',
  'border-bottom-color',
  'border-left-color',
  'border-top-left-radius',
  'border-top-right-radius',
  'border-bottom-right-radius',
  'border-bottom-left-radius',
  'border-image-source',
  'border-image-slice',
  'border-image-width',
  'border-image-outset',
  'border-image-repeat',
  // Box / effects
  'box-shadow',
  'box-sizing',
  'opacity',
  'outline-width',
  'outline-style',
  'outline-color',
  'outline-offset',
  'filter',
  'backdrop-filter',
  '-webkit-backdrop-filter',
  'clip-path',
  'mask',
  'mask-image',
  'mask-size',
  'mask-position',
  'mask-repeat',
  '-webkit-mask-image',
  'mix-blend-mode',
  'isolation',
  // Layout
  'display',
  'position',
  'top',
  'right',
  'bottom',
  'left',
  'inset',
  'width',
  'height',
  'min-width',
  'min-height',
  'max-width',
  'max-height',
  'margin',
  'margin-top',
  'margin-right',
  'margin-bottom',
  'margin-left',
  'padding',
  'padding-top',
  'padding-right',
  'padding-bottom',
  'padding-left',
  'overflow',
  'overflow-x',
  'overflow-y',
  'z-index',
  'visibility',
  'object-fit',
  'object-position',
  'aspect-ratio',
  'float',
  'clear',
  // Flex / grid (Chrome emits `grid` and `flex-flow` shorthands)
  'flex',
  'flex-flow',
  'flex-grow',
  'flex-shrink',
  'flex-basis',
  'flex-direction',
  'flex-wrap',
  'align-items',
  'align-content',
  'align-self',
  'justify-content',
  'justify-items',
  'justify-self',
  'place-content',
  'place-items',
  'place-self',
  'gap',
  'row-gap',
  'column-gap',
  'order',
  'grid',
  'grid-template',
  'grid-template-columns',
  'grid-template-rows',
  'grid-template-areas',
  'grid-auto-columns',
  'grid-auto-rows',
  'grid-auto-flow',
  'grid-area',
  'grid-column-start',
  'grid-column-end',
  'grid-row-start',
  'grid-row-end',
  'grid-column',
  'grid-row',
  // Transform
  'transform',
  'transform-origin',
  'transform-box',
  'transform-style',
  'translate',
  'rotate',
  'scale',
  'perspective',
  'perspective-origin',
  // SVG presentation
  'fill',
  'fill-opacity',
  'fill-rule',
  'stroke',
  'stroke-width',
  'stroke-dasharray',
  'stroke-dashoffset',
  'stroke-linecap',
  'stroke-linejoin',
  'stroke-miterlimit',
  'stroke-opacity',
  'vector-effect',
  'clip-rule',
  'stop-color',
  'stop-opacity',
  'flood-color',
  'flood-opacity',
  'marker-start',
  'marker-mid',
  'marker-end',
  'paint-order',
  'shape-rendering',
  'text-anchor',
  'dominant-baseline',
  'alignment-baseline',
  'baseline-shift',
  'text-rendering',
  'image-rendering',
  'color-interpolation',
  'color-interpolation-filters',
  // Misc visual
  'list-style-type',
  'list-style-position',
  'list-style-image',
  'content',
  'border-collapse',
  'border-spacing',
  'table-layout',
  'caption-side',
  'empty-cells',
]);

/**
 * Kept properties are additionally dropped when they hold their default (no-op)
 * value, since a standalone element renders the same default without them. Only
 * non-inherited properties are listed here — dropping an inherited property
 * (e.g. `fill`, `stroke`, `color`) could let an ancestor's value leak in.
 */
export const NOOP_STYLE_VALUES: Record<string, string> = {
  transform: 'none',
  translate: 'none',
  rotate: 'none',
  scale: 'none',
  filter: 'none',
  'backdrop-filter': 'none',
  '-webkit-backdrop-filter': 'none',
  'box-shadow': 'none',
  'background-image': 'none',
  mask: 'none',
  'mask-image': 'none',
  '-webkit-mask-image': 'none',
  'clip-path': 'none',
  'mix-blend-mode': 'normal',
  isolation: 'auto',
  opacity: '1',
  'z-index': 'auto',
  float: 'none',
  clear: 'none',
  position: 'static',
  top: 'auto',
  right: 'auto',
  bottom: 'auto',
  left: 'auto',
  inset: 'auto',
  'margin-top': '0px',
  'margin-right': '0px',
  'margin-bottom': '0px',
  'margin-left': '0px',
  'padding-top': '0px',
  'padding-right': '0px',
  'padding-bottom': '0px',
  'padding-left': '0px',
  'border-top-width': '0px',
  'border-right-width': '0px',
  'border-bottom-width': '0px',
  'border-left-width': '0px',
  'border-top-style': 'none',
  'border-right-style': 'none',
  'border-bottom-style': 'none',
  'border-left-style': 'none',
  'border-top-left-radius': '0px',
  'border-top-right-radius': '0px',
  'border-bottom-right-radius': '0px',
  'border-bottom-left-radius': '0px',
  'outline-width': '0px',
  'outline-style': 'none',
  'outline-offset': '0px',
  'object-fit': 'fill',
  'object-position': '50% 50%',
  'aspect-ratio': 'auto',
  'overflow-x': 'visible',
  'overflow-y': 'visible',
  'flex-grow': '0',
  'flex-shrink': '1',
  'flex-basis': 'auto',
  order: '0',
  'align-self': 'auto',
  'justify-self': 'auto',
  gap: 'normal',
  'row-gap': 'normal',
  'column-gap': 'normal',
  'grid-auto-flow': 'row',
  'background-color': 'rgba(0, 0, 0, 0)',
  'background-position': '0% 0%',
  'background-size': 'auto',
  'background-repeat': 'repeat',
  'background-origin': 'padding-box',
  'background-clip': 'border-box',
  'background-attachment': 'scroll',
  'box-sizing': 'content-box',
  // Shorthand + common non-inherited defaults
  padding: '0px',
  margin: '0px',
  'border-radius': '0px',
  grid: 'none',
  flex: '0 1 auto',
  'flex-flow': 'row',
  'grid-area': 'auto',
  'grid-template': 'none',
  'place-content': 'normal',
  'place-items': 'normal',
  'place-self': 'auto',
  'transform-style': 'flat',
  'transform-box': 'view-box',
  perspective: 'none',
  'baseline-shift': '0px',
  'alignment-baseline': 'auto',
  'dominant-baseline': 'auto',
  'stop-color': 'rgb(0, 0, 0)',
  'stop-opacity': '1',
  'flood-color': 'rgb(0, 0, 0)',
  'flood-opacity': '1',
  'background-blend-mode': 'normal',
  'table-layout': 'auto',
};
